###
GET http://localhost:8080/api/failed/job-1
Accept: application/json

###
GET http://localhost:8080/api/failed/job-2
Accept: application/json

###
GET http://localhost:8080/api/succeeded/job-1
Accept: application/json

### all available metrics
GET http://localhost:8080/actuator/metrics

### failed job-1 metrics
GET http://localhost:8080/actuator/metrics/job-1-fail?tag=status:failed

### succeeded job-1 metrics
GET http://localhost:8080/actuator/metrics/job-1-success?tag=status:succeeded
